### ISSUE TITLE
result_type of convert_documents() does not work via configs

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#19]
This does not work as expected (note that we use the generic underscore-version of the convert function):
```yaml
# in tacred_prepared.yaml
convert_documents:
  function: src.document.conversion._convert_token_based_document_with_entities_and_relations_to_text_based
  result_type: src.document.types.TokenDocumentWithLabeledEntitiesAndRelations
```
